apiVersion: v1
kind: ServiceAccount
metadata:
  name: idempotency-service-sa
  namespace: default
  annotations:
    # Annotation used by GKE Workload Identity to bind Kubernetes SA -> GCP service account
    # Replace with: iam.gke.io/gcp-service-account: "MY_GCP_SA@PROJECT.iam.gserviceaccount.com"
    iam.gke.io/gcp-service-account: "REPLACE_WITH_GCP_SA@PROJECT.iam.gserviceaccount.com"
